name: nush_modules
description: A PWA to explore modules in NUSHS.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluentui_system_icons: ^1.1.83

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
