@startuml

skinparam objectFontName Monospaced
skinparam objectAttributeFontName Monospaced
skinparam objectStereotypeFontName Monospaced

skinparam objectAttributeFontSize 16
skinparam objectFontSize 16
skinparam objectStereotypeFontSize 14

skinparam objectFontStyle bold

skinparam linetype ortho
skinparam shadowing false

object modules {
	id               : INTEGER <<PK>>
	code             : TEXT <<unique>>
	name             : TEXT
	description      : TEXT
	remarks          : TEXT <<nullable>>
	modular_credits  : INTEGER
	workload         : REAL
	subject_id       : INTEGER <<FK>>
	semester_type_id : INTEGER <<FK>>
	module_type_id   : INTEGER <<FK>>
}

object subjects {
	id       : INTEGER <<PK>>
	name     : TEXT
	color_id : INTEGER <<FK>>
}

object colors {
	id   : INTEGER <<PK>>
	name : TEXT
}

object semester_types {
	id   : INTEGER <<PK>>
	name : TEXT
}

object levels {
	id   : INTEGER <<PK>>
	year : INTEGER
}

object modules_levels <<junction table>> {
	module_id : INTEGER <<FK>>
	level_id  : INTEGER <<FK>>
}

object module_types {
	id   : INTEGER <<PK>>
	name : TEXT
}

object pinned_modules {
	id        : INTEGER <<PK, autoincrement>>
	position  : INTEGER
	module_id : INTEGER <<FK>>
}

modules }|---|| subjects
subjects }|--|| colors
modules }|--|| semester_types
modules ||-|{ modules_levels
modules_levels }|-|| levels
modules }|--|| module_types
modules ||---o| pinned_modules

object prerequisites <<self junction table>> {
	dependent_module_id    : INTEGER <<FK>>
	prerequisite_module_id : INTEGER <<FK>>
}

object corequisites <<self junction table>> {
	dependent_module_id   : INTEGER <<FK>>
	corequisite_module_id : INTEGER <<FK>>
}

object preclusions <<self junction table>> {
	precluder_module_id : INTEGER <<FK>>
	precluded_module_id : INTEGER <<FK>>
}

modules ||--|{ prerequisites
prerequisites }|--|| modules
modules ||--|{ corequisites
corequisites }|--|| modules
modules ||--|{ preclusions
preclusions }|--|| modules

@enduml

